

development:
  adapter: mysql
  database: railsnet_development
  username: root
  password:  
  host: localhost

test:
  adapter: mysql
  database: railsnet_test
  username: root
  password:  
  host: localhost



