
#production:
#    adapter: mysql
#    database: enginey_production
#    username: timothyf
#    password: 
#    host: db.fisherfamily.com

development:
  adapter: mysql
  database: enginey_development
  username: root
  password:  
  host: localhost

test:
  adapter: mysql
  database: enginey_test
  username: root
  password:  
  host: localhost



